FROM oven/bun:1-debian AS builder

WORKDIR /app

COPY package*.json bun.lock ./
RUN bun install --frozen-lockfile

COPY . .

# Build-time args for NEXT_PUBLIC_* variables (must be baked in during static export)
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_STUN_SERVER
ARG NEXT_PUBLIC_TURN_SERVER
ARG NEXT_PUBLIC_TURN_USER
ARG NEXT_PUBLIC_SENTRY_DSN
ARG NEXT_PUBLIC_SENTRY_ENVIRONMENT

ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_STUN_SERVER=$NEXT_PUBLIC_STUN_SERVER
ENV NEXT_PUBLIC_TURN_SERVER=$NEXT_PUBLIC_TURN_SERVER
ENV NEXT_PUBLIC_TURN_USER=$NEXT_PUBLIC_TURN_USER
ENV NEXT_PUBLIC_SENTRY_DSN=$NEXT_PUBLIC_SENTRY_DSN
ENV NEXT_PUBLIC_SENTRY_ENVIRONMENT=$NEXT_PUBLIC_SENTRY_ENVIRONMENT

RUN bun run build

FROM nginx:alpine

COPY --from=builder /app/out /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
